// AX bilingual content and product-series interactions; adapted from the skill site template's i18n pattern.
const i18n = {
  zh: {
    'nav.series':'产品系列','nav.science':'品牌故事','nav.moonlight':'月光礼遇','nav.ritual':'护理仪式','nav.cta':'探索 AX',
    'hero.title':'<span>一生一诺</span><span>为唯一而生</span>','hero.signature':'AX · 月光契约实验室',
    'carousel.eyebrow':'TO MY MOONLIGHT · 1314','carousel.title':'爱无需证明，<br>但值得<em>一场仪式。</em>','carousel.desc':'AX，让每一份心意都成为一份<br>可永久珍藏的契约。','carousel.slide1':'月光礼遇 · 认真抵达','carousel.slide2':'月光封缄 · 心意留存','carousel.slide3':'月光漫游 · 让故事发生','manifesto.eyebrow':'FINAL NOTE','manifesto.title':'<span>爱自己，不是买给</span><span>自己的一件礼物。</span><span class="self-love-turn">是你开始相信——</span><span>你不必为任何人改变，</span><em>也值得被好好对待。</em>','manifesto.note':'TO MY MOONLIGHT / 1314',
    'series.eyebrow':'AX 护肤精华系列','series.title':'为不同状态<br>定制一瓶精华。','series.desc':'从保湿舒缓、油脂管理，到紧致焕亮与眼周护理，AX 以六款精华回应不同肤感与护肤需求。','series.note':'请按产品包装说明使用；具体成分以产品包装标示为准。',
    'tabs.firming':'凝时紧塑','tabs.pore':'毛孔细致','tabs.clear':'净澈清肤','tabs.antiAging':'逆龄抗皱精华油','tabs.light':'光感焕颜精华油','tabs.eye':'逆龄抗皱眼部精华油',
    'story.eyebrow':'BRAND STORY','story.title':'我们相信，<br><em>值得被认真对待</em><br>是一份永恒的承诺。','story.lead':'AX 是一间关于承诺的实验室。它源于一个简单的洞察：<br>在这个速食爱情的时代，我们依然渴望一份不可撤销的证明。','story.quote':'我们让每一瓶精华为你见证——<br><em>“你值得这世间所有的美好和温柔。”</em>','story.reflection':'不是每一份心意都需要被回应。<br>但每一份真诚，都值得被好好安放。','story.closing':'AX，为每一个值得被认真对待的你，而存在。',
    'moonlight.eyebrow':'To My Moonlight 1314','moonlight.title':'凤凰入礼，<br>月光作证。','moonlight.desc':'黑金与青绿藏进每一处细节。AX 将护肤心意置于「To My Moonlight」的礼遇表达中，让重要的日子，多一份被郑重准备的光。','moonlight.n1t':'1314','moonlight.n1d':'爱情见证官','moonlight.n2t':'AX','moonlight.n2d':'献给重要的人，也献给每一次认真',
    'ritual.eyebrow':'The daily ritual','ritual.title':'让每一滴，都恰到好处。','ritual.desc':'精华液的标准护理流程：洁面、爽肤、精华、乳液或面霜锁水保湿。','ritual.s1':'洁面','ritual.s1d':'洁净肌肤后，轻拍爽肤水至吸收，让肌肤保持水润通透。','ritual.s2':'点涂','ritual.s2d':'取适量精华，均匀点涂于额头、鼻翼、脸颊与下巴。','ritual.s3':'轻柔提拉','ritual.s3d':'由内向外、由下向上轻柔按摩至吸收，避免大力拉扯肌肤。','ritual.s4':'锁住水润','ritual.s4d':'待精华吸收后，及时使用乳液或面霜锁住肌肤水分。',
    'membership.eyebrow':'For every recipient','membership.title':'成为 AX 的收礼人。','membership.desc':'我们为每一位开启月光契约的人，准备两份专属心意。','membership.g1':'初见礼','membership.g1d':'首次登录 AX 小程序并完成会员注册，可任选一款功效的 15 ml 珍萃中样。','membership.g2':'分享礼','membership.g2d':'分享至朋友圈或小红书等平台并按活动规则提交，即有机会获赠 15 ml 珍萃中样或其他礼赠。','membership.note':'具体礼遇以 AX 小程序及活动规则为准。','footer.tagline':'To My Moonlight · 献给重要的人，也献给每一次认真。'
  },
  en: {
    'nav.series':'Collection','nav.science':'Brand Story','nav.moonlight':'Moonlight Gift','nav.ritual':'Ritual','nav.cta':'Explore AX',
    'hero.title':'<span>One promise</span><span>for the one and only</span>','hero.signature':'AX · Moonlight Promise Atelier',
    'carousel.eyebrow':'TO MY MOONLIGHT · 1314','carousel.title':'Love needs no proof,<br>but deserves <em>a ceremony.</em>','carousel.desc':'AX lets every intention become<br>a promise to be treasured forever.','carousel.slide1':'Moonlight arrival · made with care','carousel.slide2':'Moonlight seal · keep the intention','carousel.slide3':'Moonlight journey · let the story unfold','manifesto.eyebrow':'FINAL NOTE','manifesto.title':'<span>Self-love is not</span><span>a gift you buy yourself.</span><span class="self-love-turn">It is the moment you believe —</span><span>you need not change for anyone,</span><em>and you deserve kind care.</em>','manifesto.note':'TO MY MOONLIGHT / 1314',
    'series.eyebrow':'AX skincare collection','series.title':'One essence<br>for every skin moment.','series.desc':'From hydration and soothing to oil balance, firming, radiance, and eye-area care, six AX essences answer different daily skincare needs.','series.note':'Use as directed on the product packaging. Refer to product packaging for the full ingredient list.',
    'tabs.firming':'Firming','tabs.pore':'Pore Refining','tabs.clear':'Clear Skin','tabs.antiAging':'Anti-Aging Oil','tabs.light':'Light Essence Oil','tabs.eye':'Eye Essence Oil',
    'story.eyebrow':'BRAND STORY','story.title':'We believe that<br><em>being treated with care</em><br>is an enduring promise.','story.lead':'AX is an atelier for promises, born from a simple insight:<br>even in a fast-moving world, we long for something that cannot be taken back.','story.quote':'We let every bottle of essence bear witness —<br><em>“You deserve all the beauty and tenderness in this world.”</em>','story.reflection':'Not every gesture needs an answer.<br>But every sincerity deserves to be held with care.','story.closing':'AX exists for everyone worthy of being treated with care.',
    'moonlight.eyebrow':'To My Moonlight 1314','moonlight.title':'A phoenix in the gift.<br>Moonlight as witness.','moonlight.desc':'Black gold and teal are carried through every detail. AX places skincare inside the To My Moonlight gesture, giving important days an added light of intention.','moonlight.n1t':'1314','moonlight.n1d':'A witness to love','moonlight.n2t':'AX','moonlight.n2d':'For someone important, and every moment treated with care',
    'ritual.eyebrow':'The daily ritual','ritual.title':'Every drop, just right.','ritual.desc':'A standard essence routine: cleanse, tone, apply essence, then use lotion or cream to seal in moisture.','ritual.s1':'Cleanse','ritual.s1d':'On clean skin, pat in toner until absorbed to keep skin hydrated and ready.','ritual.s2':'Apply','ritual.s2d':'Use an appropriate amount, dotting evenly across forehead, nose, cheeks, and chin.','ritual.s3':'Lift gently','ritual.s3d':'Massage gently from the centre outward and upward until absorbed. Avoid pulling the skin.','ritual.s4':'Seal in moisture','ritual.s4d':'After the essence absorbs, use lotion or cream to help retain moisture.',
    'membership.eyebrow':'For every recipient','membership.title':'Become an AX recipient.','membership.desc':'Two thoughtful gestures are prepared for everyone who starts a moonlight ritual with AX.','membership.g1':'First encounter gift','membership.g1d':'Complete first-time AX Mini Program registration and choose one 15 ml trial essence, subject to the applicable program terms.','membership.g2':'Sharing gift','membership.g2d':'Share on platforms such as Moments or Xiaohongshu and submit according to event rules for the opportunity to receive a 15 ml trial essence or another gift.','membership.note':'Benefits are subject to the AX Mini Program and applicable event terms.','footer.tagline':'To My Moonlight · For someone important, and every moment treated with care.'
  }
};

const demos = {
  firming:{image:'assets/product-firming-reference.png',zh:{type:'CURDLING AND FIRMING ESSENCE · 50 ML',title:'AX 凝时紧塑精华液',effect:'备案功效：保湿、抗皱、紧致',desc:'以 PROCOLL INFUSION® 智导渗透与瑞士 OXY 229 CB 酵母精粹，为肌肤带来水润呵护与紧实光彩。',ingredients:['PROCOLL INFUSION®','水解胶原 PG-丙基甲基硅烷二醇','OXY 229 CB']},en:{type:'CURDLING AND FIRMING ESSENCE · 50 ML',title:'Firming Essence',effect:'Registered claims: moisturizing, anti-wrinkle, firming',desc:'With PROCOLL INFUSION® and Swiss OXY 229 CB yeast extract, this essence is designed to moisturize and leave skin feeling smooth and firm.',ingredients:['PROCOLL INFUSION®','Modified hydrolyzed collagen','OXY 229 CB']}},
  pore:{image:'assets/product-pore-reference.png',zh:{type:'PORE REFINING ESSENCE · 50 ML',title:'AX 毛孔细致精华液',effect:'备案功效：保湿、控油',desc:'北美金缕梅水与药用层孔菌提取物的双植萃控油配方，搭配瑞士 OXY 229 CB，帮助改善油光与粗大毛孔困扰。',ingredients:['北美金缕梅水','药用层孔菌提取物','OXY 229 CB']},en:{type:'PORE REFINING ESSENCE · 50 ML',title:'Pore Refining Essence',effect:'Registered claims: moisturizing, oil control',desc:'A botanical oil-control formula with North American witch hazel water, Fomes officinalis extract, and Swiss OXY 229 CB.',ingredients:['Witch hazel water','Fomes officinalis extract','OXY 229 CB']}},
  clear:{image:'assets/product-clear-reference.png',zh:{type:'CLEAR ESSENCE · 50 ML',title:'AX 净澈清肤精华液',effect:'备案功效：保湿、舒缓',desc:'三重草本植萃配方，搭配多元醇与泛醇，为肌肤补充水分，帮助舒缓干燥紧绷感。',ingredients:['白柳树皮提取物','黄檗树皮提取物','鱼腥草提取物']},en:{type:'CLEAR ESSENCE · 50 ML',title:'Clear Essence',effect:'Registered claims: moisturizing, soothing',desc:'A triple-botanical formula with polyols and panthenol to replenish moisture and support a comfortable skin feel.',ingredients:['Willow bark extract','Phellodendron extract','Houttuynia extract']}},
  'anti-aging':{image:'assets/product-anti-aging-reference.png',zh:{type:'ANTI AGING ANTI WRINKLE ESSENCE OIL · 50 ML',title:'AX 逆龄抗皱精华油',effect:'备案功效：保湿、抗皱、紧致',desc:'融合瑞士 BisaboLife® 红没药醇、DEFENSIL 与多重植萃精油，滋润干燥肌肤，帮助提升肌肤紧实细腻感。',ingredients:['BisaboLife® 红没药醇','瑞士 DEFENSIL','三叶鬼针草提取物']},en:{type:'ANTI AGING ANTI WRINKLE ESSENCE OIL · 50 ML',title:'Anti-Aging Essence Oil',effect:'Registered claims: moisturizing, anti-wrinkle, firming',desc:'Blending Swiss BisaboLife® bisabolol, DEFENSIL, and botanical oils, it is formulated to nourish dry skin and support a smooth, firm feel.',ingredients:['BisaboLife® bisabolol','Swiss DEFENSIL','Bidens pilosa extract']}},
  light:{image:'assets/product-light-reference.png',zh:{type:'LIGHT ESSENCE OIL · 50 ML',title:'AX 光感焕颜精华油',effect:'备案功效：保湿、抗皱、紧致',desc:'搭载瑞士 OXY 229 CB 复合精粹，搭配维生素 C 与法国光滑果榆绿木树皮提取物，温和保湿修护，焕亮肤色。',ingredients:['OXY 229 CB','维生素 C','光滑果榆绿木树皮提取物']},en:{type:'LIGHT ESSENCE OIL · 50 ML',title:'Light Essence Oil',effect:'Registered claims: moisturizing, anti-wrinkle, firming',desc:'With Swiss OXY 229 CB, vitamin C, and Anogeissus leiocarpa bark extract, this formula moisturizes while supporting a radiant look.',ingredients:['OXY 229 CB','Vitamin C','Anogeissus bark extract']}},
  eye:{image:'assets/product-eye-reference.png',zh:{type:'ANTI AGING ANTI WRINKLE EYE ESSENCE OIL · 30 ML',title:'AX 逆龄抗皱眼部精华油',effect:'备案功效：保湿、抗皱、紧致',desc:'以多重植物油为基底，融合瑞士红没药醇、胜肽与植萃成分，细致呵护眼周肌肤。',ingredients:['十大植物油基底','BisaboLife® 红没药醇','胜肽复合植萃']},en:{type:'ANTI AGING ANTI WRINKLE EYE ESSENCE OIL · 30 ML',title:'Anti-Aging Eye Essence Oil',effect:'Registered claims: moisturizing, anti-wrinkle, firming',desc:'A botanical-oil base with Swiss bisabolol, peptides, and plant extracts for considered care around the eye area.',ingredients:['Ten botanical oils','BisaboLife® bisabolol','Peptide botanical blend']}}
};

let currentLang = localStorage.getItem('ax-lang') || 'zh';
let activeProduct = 'firming';
function t(key){return i18n[currentLang][key] || ''}
function renderProduct(id){activeProduct=id;const product=demos[id];const data=product[currentLang];const image=document.getElementById('product-image');image.src=product.image;image.alt=data.title;document.getElementById('product-num').textContent=`${String(Object.keys(demos).indexOf(id)+1).padStart(2,'0')} / 06`;document.getElementById('product-type').textContent=data.type;document.getElementById('product-title').textContent=data.title;document.getElementById('product-effect').textContent=data.effect;document.getElementById('product-desc').textContent=data.desc;document.getElementById('ingredient-list').innerHTML=data.ingredients.map(item=>`<span>${item}</span>`).join('');document.getElementById('product-stage').dataset.product=id;document.querySelectorAll('.product-tab').forEach(button=>{const active=button.dataset.product===id;button.classList.toggle('is-active',active);button.setAttribute('aria-selected',String(active));});}
function translatePage(){document.documentElement.lang=currentLang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-i18n]').forEach(el=>{const value=t(el.dataset.i18n);if(!value)return;if(el.dataset.i18nHtml==='true')el.innerHTML=value;else el.textContent=value;});document.getElementById('lang-toggle').textContent=currentLang==='zh'?'中 / EN':'EN / 中';renderProduct(activeProduct);}
function initCarousel(){const carousel=document.querySelector('[data-carousel]');if(!carousel)return;const stage=carousel.querySelector('[data-carousel-stage]');const slides=[...carousel.querySelectorAll('[data-carousel-slide]')];const dots=[...carousel.querySelectorAll('[data-carousel-dot]')];const previous=carousel.querySelector('[data-carousel-prev]');const next=carousel.querySelector('[data-carousel-next]');const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;let active=0;let timer;let startX=0;const show=index=>{active=(index+slides.length)%slides.length;slides.forEach((slide,slideIndex)=>{const selected=slideIndex===active;slide.classList.toggle('is-active',selected);slide.setAttribute('aria-hidden',String(!selected));});dots.forEach((dot,dotIndex)=>{const selected=dotIndex===active;dot.classList.toggle('is-active',selected);dot.setAttribute('aria-selected',String(selected));});};const stop=()=>{window.clearInterval(timer);timer=undefined;};const play=()=>{if(reduced||timer)return;timer=window.setInterval(()=>show(active+1),5500);};const restart=()=>{stop();play();};previous.addEventListener('click',()=>{show(active-1);restart();});next.addEventListener('click',()=>{show(active+1);restart();});dots.forEach(dot=>dot.addEventListener('click',()=>{show(Number(dot.dataset.carouselDot));restart();}));stage.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'){event.preventDefault();show(active-1);restart();}if(event.key==='ArrowRight'){event.preventDefault();show(active+1);restart();}});stage.addEventListener('pointerdown',event=>{startX=event.clientX;});stage.addEventListener('pointerup',event=>{const distance=event.clientX-startX;if(Math.abs(distance)<40)return;show(distance>0?active-1:active+1);restart();});carousel.addEventListener('mouseenter',stop);carousel.addEventListener('mouseleave',play);carousel.addEventListener('focusin',stop);carousel.addEventListener('focusout',event=>{if(!carousel.contains(event.relatedTarget))play();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else play();});play();}
document.addEventListener('DOMContentLoaded',()=>{translatePage();initCarousel();document.getElementById('year').textContent=new Date().getFullYear();document.getElementById('lang-toggle').addEventListener('click',()=>{currentLang=currentLang==='zh'?'en':'zh';localStorage.setItem('ax-lang',currentLang);translatePage();});document.querySelectorAll('.product-tab').forEach(button=>button.addEventListener('click',()=>renderProduct(button.dataset.product)));const nav=document.getElementById('nav');const onScroll=()=>nav.classList.toggle('is-scrolled',window.scrollY>24);window.addEventListener('scroll',onScroll,{passive:true});onScroll();});
